server:
  port: 8080
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: alpha      # 202606 update to sorts endpoints A→Z
    tags-sorter: alpha
    try-it-out-enabled: true      # enables the Try it out button by default
  api-docs:
    path: /v3/api-docs 
  show-actuator: false
  pre-loading-enabled: true          # loads spec at startup, not on first request
  packages-to-scan: com.grey.rdv_manager_api   # explicit scan path  
  #end new part
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: rdv_manager_db_202606_test
  jackson: #202606 added to define the datetime format
    serialization:
      write-dates-as-timestamps: false #end new part
  profiles:
    active: debug
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 10MB
  application:
    name: rdv_manager_api_1.0
logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    com.grey.sytsas: DEBUG
#line before here is origin config

app: # 202606 added for JWT config
  jwt:
    secret: 9d4deec43e5c4d7fd35edc20010d8f506e178721fb5aaac19e98de66fabcb423   # min 32 chars
    expiration-ms: 86400000   # 24 hours
  